FROM nowox/latex:3.0

# USER $USERNAME
# ENV USER=${USERNAME}
# RUN useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
# RUN groupadd --gid $USER_GID $USERNAME
# RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
# RUn chmod 0440 /etc/sudoers.d/$USERNAME

# Bind bashrc
# ADD .bashrc /root/.bashrc
# ADD .bashrc /home/${USERNAME}/.bashrc
